// https://www.mockaroo.com/
export const users = [
  {
    id: 1,
    first_name: "Thanos",
    last_name: "Null",
    email: "thanos.op@gmail.com",
    gender: "Male",
  },
  {
    id: 2,
    first_name: "Bethany",
    last_name: "Arp",
    email: "barp1@ft.com",
    gender: "Female",
  },
  {
    id: 3,
    first_name: "Raphael",
    last_name: "Levey",
    email: "rlevey2@seesaa.net",
    gender: "Male",
  },
  {
    id: 4,
    first_name: "Merrile",
    last_name: "Gawthrope",
    email: "mgawthrope3@edublogs.org",
    gender: "Female",
  },
  {
    id: 5,
    first_name: "Hermann",
    last_name: "McCawley",
    email: "hmccawley4@cbsnews.com",
    gender: "Male",
  },
  {
    id: 6,
    first_name: "Margarita",
    last_name: "Pinnijar",
    email: "mpinnijar5@wiley.com",
    gender: "Female",
  },
  {
    id: 7,
    first_name: "Fiona",
    last_name: "Norcliffe",
    email: "fnorcliffe6@theatlantic.com",
    gender: "Female",
  },
  {
    id: 8,
    first_name: "Gussy",
    last_name: "Wildes",
    email: "gwildes7@dropbox.com",
    gender: "Female",
  },
  {
    id: 9,
    first_name: "Pooh",
    last_name: "Thomke",
    email: "pthomke8@4shared.com",
    gender: "Female",
  },
  {
    id: 10,
    first_name: "Edd",
    last_name: "Bortolussi",
    email: "ebortolussi9@mayoclinic.com",
    gender: "Male",
  },
  {
    id: 11,
    first_name: "Corrie",
    last_name: "Roskam",
    email: "croskama@forbes.com",
    gender: "Male",
  },
  {
    id: 12,
    first_name: "Obadiah",
    last_name: "Lednor",
    email: "olednorb@slate.com",
    gender: "Male",
  },
  {
    id: 13,
    first_name: "Georgy",
    last_name: "Duesbury",
    email: "gduesburyc@icio.us",
    gender: "Male",
  },
  {
    id: 14,
    first_name: "Skippy",
    last_name: "Carrol",
    email: "scarrold@wikimedia.org",
    gender: "Male",
  },
  {
    id: 15,
    first_name: "Winni",
    last_name: "Murley",
    email: "wmurleye@mac.com",
    gender: "Non-binary",
  },
  {
    id: 16,
    first_name: "Courtnay",
    last_name: "Kollas",
    email: "ckollasf@mapy.cz",
    gender: "Genderqueer",
  },
  {
    id: 17,
    first_name: "Gerek",
    last_name: "Moorman",
    email: "gmoormang@deliciousdays.com",
    gender: "Male",
  },
  {
    id: 18,
    first_name: "Cristen",
    last_name: "Lennox",
    email: "clennoxh@google.ru",
    gender: "Female",
  },
  {
    id: 19,
    first_name: "Godwin",
    last_name: "Monkman",
    email: "gmonkmani@1688.com",
    gender: "Male",
  },
  {
    id: 20,
    first_name: "Jase",
    last_name: "Imms",
    email: "jimmsj@nbcnews.com",
    gender: "Male",
  },
];
